@startuml
skin rose
skinparam ActivityFontSize 15
skinparam ArrowFontSize 12

start
:User inputs text command to add a patient/doctor;

if () then ([command word does not exist])
    :Show error message\nfor unknown command;
else ([else])
    if () then ([missing required fields])
        :Show error message\nfor missing required fields;
    else ([else])
        if () then ([invalid field arguments])
            :Show error message\nindicating invalid field\narguments provided;
        else ([else])
            if () then ([Duplicate patient/doctor detected])
                :Show error message\nindicating duplicate patient/doctor;
                else ([else])
                    :Add the patient/doctor\ninto the persons list;
                    :Update the 'person' panel\nin the GUI;
                    :Show success message\nwith patient/doctor's information;
            endif;
        endif
    endif
endif

stop
@enduml
