@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor UI_COLOR_T4
skinparam classBackgroundColor UI_COLOR

Class "Appointment" as Appointment
Class Nric
Class AppointmentId
Class AppointmentDateTime



Appointment -down-> "1" Nric : Doctor's NRIC\t
Appointment -down-> "1" Nric : Patient's NRIC\t\t
Appointment -down-> "\t1" AppointmentDateTime
Appointment -down-> "\t1" AppointmentId


@enduml

